### ISSUE TITLE
Replace `warnings` module with `logging.warn`

### ISSUE THREAD

**Issue by marcoceppi** [Fuyukai/asyncqlio#48]
Often times I'll rely on integrity checks at the database engine level (primarily for key already exists). Unfortunately these are bubbled up with `warnings` module and not diverted to logging where I think they more appropriately fit.

If this makes sense for the project I'd be happy to swap these out.

**Comment by Fuyukai** [comment]
The warning calls are in `__del__`, which is kinda weird with logging - on interpreter shutdown, logging can cause massive stacktraces due to builtins disappearing, so doing a warning.warn is guarenteed to show up and not explode the interpreter.

**Comment by marcoceppi** [comment]
Maybe I have an older version of the library and it's been removed. I was getting it for integrity failures which I'd prefer to mite. Now it seems there are only two instances in the code base. I'll check in a few mins where I was getting it.
